import Head from "next/head";
import Image from "next/image";
import { VideoPlayer } from "../components/VideoPlayer";
import styles from "../styles/Home.module.css";

const source =
  "https://livepeercdn.com/recordings/687537da-3b51-414a-9643-9738fffa86ed/index.m3u8";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Custom Video Player</h1>

        <VideoPlayer width={600} height={400} src={source} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
